### ISSUE TITLE
DIO_MCX 16 panel

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/DIO_MCX#1]
Is such a panel description clear enough?
![obraz](https://user-images.githubusercontent.com/4325054/65081630-54146f00-d9a4-11e9-9880-49536357015e.png)

The board fits nicely in 4HP
![obraz](https://user-images.githubusercontent.com/4325054/65081691-7ad2a580-d9a4-11e9-8589-4d59eb52169d.png)
![obraz](https://user-images.githubusercontent.com/4325054/65081713-8d4cdf00-d9a4-11e9-90a6-8337d2cafb60.png)

**Comment by jordens** [comment]
I would do the numbering (and therefore also the grouping) in the usual row-major format, and not column-major. We use row major everywhere I believe.

Can we drop the "Not isolated"? There is no expectation that every module provides isolated channels. In fact, the only isolated modules are DIO_SMA and DIO_BNC. The rest are at most differential or pseudo-differential.

You could also use that new MCX-BNC piggy back module instead of the custom mezzanine here. That increases it's use base, reduced the number of boards we have (or at least board area, if you make this one a break-off). Maybe there are LED packages that work with that arrangement.

**Comment by gkasprow** [comment]
Thanks for the feedback. The tiny mezzanine won't fit and of course, LEDs would be an issue.  I tried it already :)

**Comment by gkasprow** [comment]
next iteration
![obraz](https://user-images.githubusercontent.com/4325054/65188289-5cd17780-da6e-11e9-858b-b826c023bcd0.png)

**Comment by gkasprow** [comment]
I can also place the red LED that indicates a direction, always on top of each quad group

**Comment by jordens** [comment]
That would be nice. And my guess is that the group frame close to the panel sides will be hard to produce. Just horizontal lines to separate the groups would be sufficient IMO

**Comment by gkasprow** [comment]
true.

**Comment by jordens** [comment]
Also make sure that the MCX placement in the panel is correct. On Stabilizer they were misaligned.
https://github.com/sinara-hw/Stabilizer/issues/11

**Comment by hartytp** [comment]
nice!

**Comment by gkasprow** [comment]
I can fit the frame as well
![obraz](https://user-images.githubusercontent.com/4325054/65284231-42180500-db39-11e9-911a-365942689b1e.png)
